// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>

int main(){
    int fib_last = 1;
    int fib_current = 1;

    int sum = 0;

    while(fib_current < 4000000){
        if(fib_current % 2 == 0) sum += fib_current;
        int tmp = fib_current;
        fib_current += fib_last;
        fib_last = tmp;
    }

    std::cout << sum << std::endl;


    return 0;
}